name: Pseudochannel_gen
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.10.0=py314h06a4308_0
  - aom=3.12.1=h7934f7d_0
  - argon2-cffi=25.1.0=py314h06a4308_0
  - argon2-cffi-bindings=25.1.0=py314hee96239_0
  - asttokens=3.0.0=py314h06a4308_0
  - async-lru=2.0.5=py314h06a4308_0
  - attrs=25.4.0=py314h06a4308_2
  - babel=2.17.0=py314h06a4308_0
  - beautifulsoup4=4.14.2=py314h06a4308_0
  - blas=1.0=mkl
  - bleach=6.3.0=py314h06a4308_0
  - bottleneck=1.4.2=py314h6a40391_1
  - brotlicffi=1.2.0.0=py314h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2026.01.04=py314h06a4308_0
  - cffi=2.0.0=py314h4eded50_1
  - charset-normalizer=3.4.4=py314h06a4308_0
  - comm=0.2.3=py314h06a4308_0
  - contourpy=1.3.3=py314hdb19cb5_0
  - cycler=0.12.1=py314h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.16=py314hbdd6827_1
  - decorator=5.2.1=py314h06a4308_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=py314h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.61.0=py314h47b2149_0
  - freetype=2.14.1=hf5b9546_0
  - fribidi=1.0.16=h9fb5f84_0
  - graphite2=1.3.14=h295c915_1
  - h11=0.16.0=py314h06a4308_1
  - harfbuzz=12.3.0=h79d275a_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py314h06a4308_0
  - httpx=0.28.1=py314h06a4308_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py314h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=6.31.0=py314h6fa48dc_0
  - ipympl=0.9.8=py314h06a4308_0
  - ipython=9.7.0=py314h06a4308_0
  - ipython_pygments_lexers=1.1.1=py314h06a4308_0
  - ipywidgets=8.1.7=py314h06a4308_0
  - jedi=0.19.2=py314h06a4308_0
  - jinja2=3.1.6=py314h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - json5=0.12.1=py314h06a4308_0
  - jsonschema=4.25.1=py314h06a4308_0
  - jsonschema-specifications=2025.9.1=py314h06a4308_0
  - jupyter=1.1.1=py314h06a4308_0
  - jupyter-lsp=2.2.5=py314h06a4308_0
  - jupyter_client=8.8.0=py314h06a4308_0
  - jupyter_console=6.6.3=py314h06a4308_1
  - jupyter_core=5.9.1=py314h06a4308_0
  - jupyter_events=0.12.0=py314h06a4308_1
  - jupyter_server=2.17.0=py314h06a4308_0
  - jupyter_server_terminals=0.5.3=py314h06a4308_0
  - jupyterlab=4.5.0=py314h06a4308_0
  - jupyterlab_pygments=0.3.0=py314h06a4308_0
  - jupyterlab_server=2.28.0=py314h06a4308_0
  - jupyterlab_widgets=3.0.15=py314h06a4308_0
  - kiwisolver=1.4.9=py314h24d9097_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.3.0=h3539ee5_0
  - libdeflate=1.22=h5eee18b_0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libglib=2.86.3=h8b17d9a_0
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libmpdec=4.0.0=h5eee18b_0
  - libopenjpeg=2.5.4=hee96239_1
  - libpng=1.6.54=hee55ce4_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h029b1ac_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py314h5eee18b_0
  - matplotlib-base=3.10.8=py314h54cb298_0
  - matplotlib-inline=0.2.1=py314h06a4308_0
  - mistune=3.1.2=py314h06a4308_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py314hacdc0fc_0
  - mkl_fft=2.1.1=py314h2be417e_0
  - mkl_random=1.3.0=py314hda4e5d8_0
  - nbclient=0.10.2=py314h06a4308_0
  - nbconvert=7.16.6=py314h06a4308_0
  - nbconvert-core=7.16.6=py314h06a4308_0
  - nbconvert-pandoc=7.16.6=py314h06a4308_0
  - nbformat=5.10.4=py314h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=7.5.0=py314h06a4308_0
  - notebook-shim=0.2.4=py314h06a4308_0
  - numexpr=2.14.1=py314hc3af6af_0
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py314h06a4308_1
  - pandas=2.3.3=py314hda4e5d8_1
  - pandoc=3.8=h06a4308_0
  - pandocfilters=1.5.1=py314h06a4308_0
  - parso=0.8.5=py314h06a4308_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=py314h06a4308_1
  - pillow=12.1.0=py314hd9fd23a_0
  - pip=25.3=pyh0d26453_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=py314h06a4308_0
  - prometheus_client=0.21.1=py314h06a4308_0
  - prompt-toolkit=3.0.52=py314h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py314hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py314h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.2=py314h06a4308_0
  - pyparsing=3.2.5=py314h06a4308_0
  - pysocks=1.7.1=py314h06a4308_1
  - python=3.14.2=h90eec9f_101_cp314
  - python-dateutil=2.9.0post0=py314h06a4308_2
  - python-fastjsonschema=2.21.2=py314h06a4308_0
  - python-json-logger=4.0.0=py314h06a4308_0
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - python_abi=3.14=2_cp314
  - pytz=2025.2=py314h06a4308_0
  - pyyaml=6.0.3=py314h591646f_0
  - pyzmq=27.1.0=py314hcf8288c_1
  - qtconsole=5.7.0=py314h06a4308_0
  - qtpy=2.4.3=py314h06a4308_0
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=py314h06a4308_0
  - requests=2.32.5=py314h06a4308_1
  - rfc3339-validator=0.1.4=py314h06a4308_0
  - rfc3986-validator=0.1.1=py314h06a4308_0
  - rpds-py=0.28.0=py314h498d7c9_0
  - seaborn=0.13.2=py314h06a4308_3
  - send2trash=1.8.3=py314h06a4308_0
  - setuptools=80.10.1=py314h06a4308_0
  - six=1.17.0=py314h06a4308_0
  - sniffio=1.3.1=py314h06a4308_0
  - soupsieve=2.5=py314h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - stack_data=0.6.3=py314h06a4308_0
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - terminado=0.18.1=py314h06a4308_0
  - tifffile=2025.12.20=py314h06a4308_0
  - tinycss2=1.4.0=py314h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.4=py314h47b2149_0
  - traitlets=5.14.3=py314h06a4308_0
  - typing-extensions=4.15.0=py314h06a4308_0
  - typing_extensions=4.15.0=py314h06a4308_0
  - tzdata=2025c=he532380_0
  - urllib3=2.6.3=py314h06a4308_0
  - wcwidth=0.2.14=py314h06a4308_0
  - webencodings=0.5.1=py314h06a4308_2
  - websocket-client=1.8.0=py314h06a4308_0
  - widgetsnbextension=4.0.14=py314h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - cellpose==3.1.1.2
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.3.3
      - fastremap==1.17.7
      - filelock==3.20.3
      - fill-voids==2.1.1
      - fsspec==2026.1.0
      - imagecodecs==2026.1.14
      - llvmlite==0.46.0
      - mpmath==1.3.0
      - natsort==8.4.0
      - networkx==3.6.1
      - numba==0.63.1
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python-headless==4.13.0.90
      - roifile==2026.1.29
      - scipy==1.17.0
      - segment-anything==1.0
      - sympy==1.14.0
      - torch==2.10.0
      - torchvision==0.25.0
      - tqdm==4.67.2
      - triton==3.6.0
prefix: /home/ubuntu/miniconda3/envs/Pseudochannel_gen
